# Generated by Django 3.1.5 on 2021-01-20 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikipedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='zipcode',
            field=models.IntegerField(),
        ),
    ]
