# Generated by Django 3.1.5 on 2021-01-20 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wikipedia', '0003_remove_registration_zipcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='address',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='city',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='email',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='password',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='state',
        ),
    ]
