# Generated by Django 3.1.5 on 2021-01-27 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikipedia', '0005_auto_20210120_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploaddata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('comments', models.CharField(max_length=50)),
                ('fileupload', models.FileField(upload_to=500)),
            ],
        ),
    ]
