# Generated by Django 3.1.5 on 2021-02-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikipedia', '0007_auto_20210127_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('feedback', models.CharField(max_length=500)),
            ],
        ),
    ]
